services:
  - type: web
    name: agf-coleta
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python servidor.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
