var DADOS_CONFIG_INVENTARIO = {
    projeto: {
        id: 'inventario',
        nome: 'Inventário Florestal',
        descricao: 'Coleta de dados de inventário florestal',
        box_folder_id: '400201285976',
        box_geojson_folder: '400216557385',
        criado_em: '2026-07-15'
    },
    camadas: {
        Censo: {
            nome: 'Censo Arbóreo',
            icone: 'tree',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso Prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO_GPS', label: 'Número GPS', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'FUSTE', label: 'Fuste (ex: 1 de 3)', tipo: 'fuste_grupo', obrigatorio: true },
                { nome: 'ALTURA', label: 'Altura', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'CAP', label: 'CAP', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D1', label: 'COPA D1', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D2', label: 'COPA D2', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'NOME_VULGAR', label: 'Nome vulgar', tipo: 'texto', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'EPIFITAS', label: 'Epifitas', tipo: 'textarea', obrigatorio: true },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATIV', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VERT_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VERT_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Parcela_Arboreo: {
            nome: 'Parcela Arbóreo',
            icone: 'forest',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'TAMANHO_DA_PARCELA', label: 'Tamanho da parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'FUSTE', label: 'Fuste (ex: 1 de 3)', tipo: 'fuste_grupo', obrigatorio: true },
                { nome: 'ALTURA', label: 'Altura', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'CAP', label: 'CAP', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D1', label: 'COPA D1', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D2', label: 'COPA D2', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'NOME_COMUM', label: 'Nome Comum', tipo: 'texto', obrigatorio: true },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'EPIFITAS', label: 'Epifitas', tipo: 'textarea', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATIV', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VERT_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VERT_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Parcela_Arbustivo: {
            nome: 'Parcela Arbustivo',
            icone: 'bush',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'TAMANHO_DA_PARCELA', label: 'Tamanho da parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'FUSTE', label: 'Fuste (ex: 1 de 3)', tipo: 'fuste_grupo', obrigatorio: true },
                { nome: 'ALTURA', label: 'Altura', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'CAP', label: 'CAP', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'NOME_COMUM', label: 'Nome Comum', tipo: 'texto', obrigatorio: true },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATIV', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VERT_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VERT_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Parcela_Herbaceo: {
            nome: 'Parcela Herbáceo',
            icone: 'herb',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'TAMANHO_DA_PARCELA', label: 'Tamanho da parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'PORCENTAGEM_COBERTA_ESPECIE', label: '% Coberta pela espécie', tipo: 'texto', obrigatorio: true },
                { nome: 'NOME_COMUM', label: 'Nome Comum', tipo: 'texto', obrigatorio: true },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATIV', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VERT_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VERT_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Parcela_Arbustivo_CR: {
            nome: 'Parcela Arbustivo CR',
            icone: 'bush',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'TAMANHO_DA_PARCELA', label: 'Tamanho da parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'FUSTE', label: 'Fuste (ex: 1 de 3)', tipo: 'fuste_grupo', obrigatorio: true },
                { nome: 'ALTURA', label: 'Altura', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'CAP', label: 'CAP', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D1', label: 'COPA D1', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'COPA_D2', label: 'COPA D2', tipo: 'fuste_campo', obrigatorio: true },
                { nome: 'NOME_COMUM', label: 'Nome Comum', tipo: 'texto', obrigatorio: true },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATIV', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VERT_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VERT_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Parcela_Herbaceo_CR: {
            nome: 'Parcela Herbáceo CR',
            icone: 'herb',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'RESPONSAVEL_DE_CAMPO', label: 'Responsável De Campo', tipo: 'texto', obrigatorio: true },
                { nome: 'IDENTIFICADOR_DE_CAMPO', label: 'Identificador de campo', tipo: 'texto', obrigatorio: true },
                { nome: 'LOCALIDADE', label: 'Localidade', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true },
                { nome: 'TAMANHO_DA_PARCELA', label: 'Tamanho da parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'SUBPARCELA', label: 'Subparcela', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMERO', label: 'Número', tipo: 'texto', obrigatorio: true },
                { nome: 'PORCENTAGEM_COBERTA_ESPECIE', label: '% Coberta pela espécie', tipo: 'texto', obrigatorio: true },
                { nome: 'NOME_COMUM', label: 'Nome Comum', tipo: 'texto', obrigatorio: true },
                { nome: 'FOTO', label: 'Foto', tipo: 'texto', obrigatorio: true },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false },
                { nome: 'NOME_CIENTIFICO', label: 'Nome científico', tipo: 'texto', obrigatorio: true },
                { nome: 'FAMILIA', label: 'Família', tipo: 'texto', obrigatorio: true },
                { nome: 'ORIGEM_NATU_EXO_NATI', label: 'Origem (naturalizada, exótica ou nativa)', tipo: 'lista', obrigatorio: true, opcoes: ['Nativa', 'Exótica', 'Naturalizada'] },
                { nome: 'STATUS', label: 'Status', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_X_VART_A', label: 'Coordenada X Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'COORD_Y_VART_A', label: 'Coordenada Y Vértice A', tipo: 'texto', obrigatorio: true },
                { nome: 'USO_SOLO', label: 'Uso do solo', tipo: 'texto', obrigatorio: true }
            ]
        },
        Caracterizacao_FESD: {
            nome: 'Caracterização FESD',
            icone: 'camera',
            campos: [
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'USO_PREVIO', label: 'Uso prévio', tipo: 'texto', obrigatorio: true, placeholder: 'Classificar o estágio sucessional...' },
                { nome: 'NUMERO_ESTRATOS', label: 'Número de Estratos', tipo: 'texto', obrigatorio: true },
                { nome: 'EPIFITAS', label: 'Epifitas', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'ORQUIDEAS', label: 'Orquídeas', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'BROMELIAS', label: 'Bromélias', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'MUSGOS_LIQUENS', label: 'Musgos e Líquens', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'SERRAPILHEIRA', label: 'Serrapilheira', tipo: 'lista', obrigatorio: true, opcoes: ['Rala', 'Pouca', 'Moderada', 'Densa'] },
                { nome: 'TREPADEIRAS_LENHOSAS', label: 'Trepadeiras Lenhosas', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'TREPADEIRAS_HERBACEA', label: 'Trepadeiras Herbáceas', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'DENSIDADE_DE_ARBUSTOS', label: 'Densidade de Arbustos', tipo: 'lista', obrigatorio: true, opcoes: ['Ausente', 'Poucas', 'Moderado', 'Abundante'] },
                { nome: 'RELEVO', label: 'Relevo', tipo: 'texto', obrigatorio: true },
                { nome: 'ANTROPIZACAO', label: 'Antropização', tipo: 'textarea', obrigatorio: true, placeholder: 'Quais antropizações verificadas (incêndio, efeito de borda, presença de exóticas, vestígios de animais domésticos)' },
                { nome: 'OBSERVACOES', label: 'Observações', tipo: 'textarea', obrigatorio: false }
            ]
        },
        Caracterizacao_Cerrado: {
            nome: 'Caracterização Cerrado',
            icone: 'camera',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'ANALISE_PAISA_PRE_EX', label: 'Análise Paisagística Pré-Existente', tipo: 'texto', obrigatorio: true, placeholder: 'explícita, considerável, alguma, não considerada' },
                { nome: 'PORCENT_COBER_HERBA_ARBUS', label: 'Percentual Cobertura Herbácea/Arbustiva (%)', tipo: 'texto', obrigatorio: true, placeholder: '1 - < 50 %, 2 - > 50 %' },
                { nome: 'PORCENT_SOLO_EXPOSTO', label: 'Percentual Solo Exposto (%)', tipo: 'texto', obrigatorio: true, placeholder: '1 - > 50%, 3 - 31 a 50%, 6 - 10 e 30%, 10 - < 10%' },
                { nome: 'PORCENT_COBERT_DO_SOLO_SERRAP', label: 'Percentual Cobertura do Solo/Serrapilheira (%)', tipo: 'texto', obrigatorio: true, placeholder: '1 - > 50%, 3 - 31 a 50%, 6 - 10 e 30%, 10 - < 10%' },
                { nome: 'ANTROPIZACAO_DA_AREA_TIPO', label: 'Antropização da Área (Tipo)', tipo: 'texto', obrigatorio: true, placeholder: 'incêndio, supressão, gado, mineração, estradas/trilhas...' },
                { nome: 'ANTROPIZACAO_DA_AREA_INTENS', label: 'Antropização da Área (Intensidade)', tipo: 'texto', obrigatorio: true, placeholder: '1 - > 50%, 2 - 30 e 50%, 3 - 10 e 30%, 4 - < 10%' },
                { nome: 'ANALISE_PAISAGEM_FITOFISIONOM', label: 'Análise da Paisagem - Fitofisionomia', tipo: 'texto', obrigatorio: true, placeholder: 'capão, brejo, lajeado, campo sujo, campo limpo, etc...' }
            ]
        },
        Caracterizacao_CR: {
            nome: 'Caracterização CR',
            icone: 'camera',
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'PARCELA', label: 'Parcela', tipo: 'texto', obrigatorio: true },
                { nome: 'HISTORICO_USO', label: 'Histórico de Uso', tipo: 'textarea', obrigatorio: true, placeholder: 'remanescentes de vegetação campestre com porção subterrânea incipiente ou ausente; áreas que sofreram ação antrópica com pouco ou nenhum comprometimento da parte subterrânea da vegetação, ou que estejam em processo de regeneração após ação antrópica mediante supressão da parte aérea e subterrânea da vegetação; áreas com ação antrópica moderada sem comprometimento da estrutura e fisionomia da vegetação, ou que tenham evoluído a partir de estágios médios de regeneração; vegetação de máxima expressão local, sendo os efeitos das ações antrópicas mínimos' },
                { nome: 'COBER_VEGE_VIVA_SOLO', label: 'Cobertura Vegetal Viva do Solo', tipo: 'texto', obrigatorio: true, placeholder: '<50%, >50% a 65%, >65% a 80%, >80%' },
                { nome: 'TIPO_SUBSTRATO', label: 'Tipo de Substrato', tipo: 'texto', obrigatorio: true, placeholder: 'Quartzítico, Canga nodular, Canga couraçada' },
                { nome: 'GEOAMBIENTE', label: 'Geoambiente', tipo: 'texto', obrigatorio: true, placeholder: 'Aberto, Arbustivo, Capão' },
                { nome: 'ESPECIES_LENHOSAS', label: 'Espécies Lenhosas', tipo: 'texto', obrigatorio: true, placeholder: 'nenhuma, poucas, muitas...' },
                { nome: 'OBSERVACAO', label: 'Observação', tipo: 'textarea', obrigatorio: false }
            ]
        },
        Floristica_Caminhamento_CR: {
            nome: 'Florística Caminhamento CR',
            icone: 'flower',
            autoObservacao: false,
            campos: [
                { nome: 'DATA', label: 'Data', tipo: 'data', obrigatorio: true },
                { nome: 'LOCALIDADE_REFERENCIA', label: 'Localidade - referência', tipo: 'texto', obrigatorio: true },
                { nome: 'TIPO_DE_REGISTRO', label: 'Tipo de Registro', tipo: 'texto', obrigatorio: true },
                { nome: 'GPS', label: 'GPS', tipo: 'texto', obrigatorio: true },
                { nome: 'FENOLOGIA', label: 'Fenologia', tipo: 'texto', obrigatorio: true },
                { nome: 'HABITAT', label: 'Habitat', tipo: 'texto', obrigatorio: true },
                { nome: 'NUMEROS_DE_INDIVIDUOS', label: 'Número de indivíduos', tipo: 'numero', obrigatorio: true },
                { nome: 'ESPECIE', label: 'Espécie', tipo: 'texto', obrigatorio: true }
            ]
        }
    }
};
